### ISSUE TITLE
Change preview screenshot

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/rails_admin_content_builder#11]

**Comment by gabrielmedina** [comment]
Cool! We need update example project to generate new preview screenshot 🍺

**Comment by gabrielmedina** [comment]
Hi my friend. This screenshot is approved?

![content-min](https://cloud.githubusercontent.com/assets/2979365/20011834/b0c61e4a-a28b-11e6-955c-cc487f43a880.jpg)

**Comment by luizpicolo** [comment]
Approved :ghost:

**Comment by gabrielmedina** [comment]
Finished #14
