### ISSUE TITLE
Erro ao fazer upload da imagem

### ISSUE THREAD

**Issue by vldsoar** [luizpicolo/rails_admin_content_builder#20]
A imagem não carrega. 

![sem titulo](https://cloud.githubusercontent.com/assets/22404789/22048957/21d6d008-dd0f-11e6-85db-c6e95efbf0b6.png)

Se mantém assim: 

![sem titulo2](https://cloud.githubusercontent.com/assets/22404789/22048985/53928e02-dd0f-11e6-8b35-addfe40a4fe2.png)

**Comment by luizpicolo** [comment]
Bom dia @vldsoar .
Se você seguiu corretamente todos os passos, imagino que, provavelmente, possa ser um erro da Gem, talvez algo relacionado a ordem do carregamento JavaScript. Contudo, até o momento não tivemos nenhum erro parecido. Vou gerar um novo projeto para teste logo que possível.

**Comment by vldsoar** [comment]
Bom dia @luizpicolo 

Estou no aguardo.

**Comment by vldsoar** [comment]
@luizpicolo Após eu dá um console log na imagem, vi que o erro na verdade era na minha biblioteca de processamento de imagem, que o MiniMagick utiliza. 

Atualizei e deu tudo certo.  Desculpa o incômodo.

Abraço.

**Comment by luizpicolo** [comment]
Perfeito @vldsoar, acreditei mesmo que seria algo local e não com a Gem. Aproveite e qualquer coisa entre em contato. Aproveita para conhecer também o [Featured_Content](https://github.com/luizpicolo/rails_admin_featured_content)

**Comment by kxu1988** [comment]
I happend to the same error. @luizpicolo @vldsoar 
and I edit this page to "rails_admin_content_builder/app/assets/javascripts/rails_admin/helpers/get_image_of_position.js"
remove 'image' from this code 'return e.image.left_or_right.url;'

like this:
`      return e.left_or_right.url;
`
